create table user_books
(
    id      bigint generated by default as identity
        primary key,
    book_id bigint
        constraint fka26s0po2ld5t5mi5sww9ca98
            references books,
    user_id bigint
        constraint fkseruwi8quqdx6svnurcamej55
            references users
);